version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12 # (1)
    commands:
      - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin  # (2)
  pre_build:
    commands:
      - npm install # (3)
      - npm test # (4)
  build:
    commands:
      - pwd
      - docker build -t docker.io/smithanjohn85/test-sample:latest -f ./Dockerfile . #(5)
  post_build:
    commands:
      - docker push docker.io/smithanjohn85/test-sample:latest